name: Examples
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v4
      
      - name: Gitbook Action
        uses: ZanderZhao/gitbook-action@v1.2.4
        with:
          token: ${{ secrets.GITBOOK }} 
          time_zone: Asia/Shanghai
          source_branch: main
          source_dir: examples/raw
          source_edit_time: true
          publish_dir: examples
          publish_branch: main
